<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvoawoD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvoawoD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSvoawoD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSvoawoD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSvoawoD\App_KernelDevDebugContainer([
    'container.build_hash' => 'SvoawoD',
    'container.build_id' => 'bdbd0291',
    'container.build_time' => 1670152301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSvoawoD');
