<?php

namespace ContainerSvoawoD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CHlFW8oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CHlFW8o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CHlFW8o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MainController::createBlog' => ['privates', '.service_locator.rpRf0Bp', 'get_ServiceLocator_RpRf0BpService', true],
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.8af4n9B', 'get_ServiceLocator_8af4n9BService', true],
            'App\\Controller\\MainController::listBlog' => ['privates', '.service_locator.8af4n9B', 'get_ServiceLocator_8af4n9BService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\MainController:createBlog' => ['privates', '.service_locator.rpRf0Bp', 'get_ServiceLocator_RpRf0BpService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.8af4n9B', 'get_ServiceLocator_8af4n9BService', true],
            'App\\Controller\\MainController:listBlog' => ['privates', '.service_locator.8af4n9B', 'get_ServiceLocator_8af4n9BService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\MainController::createBlog' => '?',
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\MainController::listBlog' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\MainController:createBlog' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\MainController:listBlog' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
